{
 "title": "Prometheus Flask Example Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests in Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_request_in_progress{app=\"sbd-prometheus-flask-app\"})"
    }
   ]
  },
  {
   "title": "Total API requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{app=\"sbd-prometheus-flask-app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Unique users visited",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (user) (rate(flask_app_total_auths_total{app=\"sbd-prometheus-flask-app\"}[$__range])))\r",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "API calls by user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user) (rate(flask_app_total_auths_total{app=\"sbd-prometheus-flask-app\"}[$__range]))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Even number input distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (flask_app_even_numbers_bucket{container=\"sbd-prometheus-flask-app\"})"
    }
   ]
  }
 ]
}