{{- if .Values.podMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
spec:
  podTargetLabels:
  - app
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  podMetricsEndpoints:
  - port: {{ .Values.podMonitor.port }}
    path: {{ .Values.podMonitor.path }}
    {{- with .Values.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
{{- end }}
